### ISSUE TITLE
A9LH payloads with arm11 entrypoints converted with firmy do not work

### ISSUE THREAD

**Issue by RealMemeShack** [RealMemeShack/firmy#1]
Investigating...

**Comment by RealMemeShack** [comment]
Hmm, it seems when verifying the firm with GM9, it warns that the arm11 entrypoint is missing

**Comment by RealMemeShack** [comment]
Also, when booting it with GM9 it freezes GM9

**Comment by RealMemeShack** [comment]
This seems to only happen with payloads that have both arm9 and arm11 entrypoints. This works fine with only arm9 entrypoint payloads

**Comment by RealMemeShack** [comment]
GarnetSunset_Work#9856 suggested that instead of converting the binary, firmy will obtain the source of the payload, and modify it for b9s @GarnetSunset

**Comment by RealMemeShack** [comment]
Kitlith#3594 explained that a9lh assumes arm11 is in a loop and waiting for an address to jump to. They said that if we were to make the a9lh payload provide it's own arm11 payload, we would need to provide the loop.

**Comment by kitling** [comment]
https://github.com/AuroraWright/arm9loaderhax/blob/master/payload_stage2/arm11/source/main.c

This is the code used for arm9loaderhax.

**Comment by RealMemeShack** [comment]
I've concluded that firmy will not be able to convert payloads with both entrypoints.
